version: '2'

services:
  node:
    build: node
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
